CREATE DATABASE sparquitecturamicroserviciobp;
USE sparquitecturamicroserviciobp;

CREATE TABLE `persona` (
  `ID_PERSONA` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_PERSONA` varchar(200) DEFAULT NULL,
  `EDAD_PERSONA` int DEFAULT NULL,
  `IDENTIFICACION_PERSONA` varchar(13) DEFAULT NULL,
  `DIRECCION_PERSONA` varchar(200) DEFAULT NULL,
  `TELEFONO_PERSONA` varchar(13) DEFAULT NULL,
  `GENERO_PERSONA` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_PERSONA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cliente` (
  `ID_CLIENTE` int NOT NULL AUTO_INCREMENT,
  `ID_PERSONA` int DEFAULT NULL,
  `CONTRASENA_CLIENTE` varchar(100) DEFAULT NULL,
  `ESTADO_CLIENTE` int DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  KEY `FK_RELATIONSHIP_3` (`ID_PERSONA`),
  CONSTRAINT `FK_RELATIONSHIP_3` FOREIGN KEY (`ID_PERSONA`) REFERENCES `persona` (`ID_PERSONA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cuenta` (
  `ID_CUENTA` int NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int DEFAULT NULL,
  `NUMERO_CUENTA` int DEFAULT NULL,
  `TIPO_CUENTA` int DEFAULT NULL,
  `SALDO_INICIAL_CUENTA` float(10,2) DEFAULT NULL,
  `ESTADO_CUENTA` int DEFAULT NULL,
  PRIMARY KEY (`ID_CUENTA`),
  KEY `FK_RELATIONSHIP_2` (`ID_CLIENTE`),
  CONSTRAINT `FK_RELATIONSHIP_2` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `movimiento` (
  `ID_MOVIMIENTO` int NOT NULL AUTO_INCREMENT,
  `ID_CUENTA` int DEFAULT NULL,
  `FECHA_MOVIMIENTO` datetime DEFAULT NULL,
  `TIPO_MOVIMIENTO` varchar(100) DEFAULT NULL,
  `SALDO_MOVIMIENTO` float(10,2) DEFAULT NULL,
  `ESTADO_MOVIMIENTO` int DEFAULT NULL,
  `DESCRIPCION_MOVIMIENTO` varchar(200) DEFAULT NULL,
  `SALDO_ACTUAL_MOVIMIENTO` float(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID_MOVIMIENTO`),
  KEY `FK_REFERENCE_3` (`ID_CUENTA`),
  CONSTRAINT `FK_REFERENCE_3` FOREIGN KEY (`ID_CUENTA`) REFERENCES `cuenta` (`ID_CUENTA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `estado` (
  `ID_ESTADO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION_ESTADO` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tipocuenta` (
  `ID_TIPOCUENTA` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION_TIPOCUENTA` varchar(100) DEFAULT NULL,
  `ESTADO_TIPOCUENTA` int DEFAULT NULL,
  PRIMARY KEY (`ID_TIPOCUENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `tipocuenta` VALUES (1,'Ahorro',1),(2,'Corriente',1);
INSERT INTO `estado` VALUES (1,'Activo'),(2,'Inactivo');
